#!/bin/bash

set -e
composer --version >/dev/null 2>&1 || {
  tmp=$(mktemp)
  curl -sSL https://getcomposer.org/installer -o ${tmp}
  php ${tmp} --install-dir=/usr/local/bin --filename=composer
  composer global require hirak/prestissimo
}
