#!/bin/bash

composer --version >/dev/null 2>&1 || {
  tmp=$(mktemp)
  curl -sSL https://getcomposer.org/installer -o ${tmp}
  php ${tmp} --filename=/usr/local/bin/composer
  composer global require hirak/prestissimo
}
