#!/bin/bash
set -e
set -x
npm --version > /dev/null 2>&1 || {
    tmpFile=$(mktemp)
		curl -sSL https://deb.nodesource.com/setup_10.x -o ${tmpFile}
    bash ${tmpFile}
		apt install -y nodejs
    rm -f ${tmpFile}
}
