#!/bin/bash

set_root() {
  local this=$(readlink -n -f $1)
  local bin=$(dirname $this)
  root=$(dirname $(dirname $bin))
}

set_root $0
cd ${root}/tests/docker

BUILD_VERSION=$(git describe --exact-match --tags $(git log -n1 --pretty='%h') 2>/dev/null || echo local-dev)
BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
VCS_REF=$(git rev-parse HEAD)

export BUILD_VERSION
export BUILD_DATE
export VCS_REF

docker-compose $@
